export const CITY_MAP: Record<string, string> = {
  QBC: "Quebec",
  QCB: "Quebec",
  VIC: "Victoriaville",
  SHK: "Sherbrooke",
  TOR: "Toronto",
  EDM: "Edmonton",
  LGL: "Longueuil",
  LVL: "Laval",
  VAL: "Valleyfield",
  OTT: "Ottawa",
  MTL: "Montreal",
  MLT: "Montreal",
  GTO: "Gatineau",
  MOC: "Moncton",
  TRR: "Trois-Rivieres",
  CBG: "Chibougamau",
  DRU: "Drummondville",
};
